root: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    jsx: false
  project:
    - ./tsconfig.json
env:
  es6: true
  node: true
  jest: true
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:node/recommended
  - standard
rules:
  node/no-unsupported-features/es-syntax:
    - error
    - ignores:
        - modules
  node/no-missing-import:
    - off
  "@typescript-eslint/no-explicit-any":
    - off
overrides:
  - files:
      - "**/tools/**/*.ts"
      - "**/tests/**/*.ts"
    rules:
      no-console:
        - off
